# Application configuration
spring:
  application:
    name: LibReserve

  # Database configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  # Email configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server configuration
server:
  port: ${PORT:8000}

# JWT configuration
jwt:
  key: ${JWT_SECRET_KEY}
  expirationTime: ${JWT_EXPIRATION_TIME:120}

# Logging configuration
logging:
  level:
    org:
      springframework:
        security: DEBUG

# Library specific configuration
library:
  properties:
    universityUrl: ${UNIVERSITY_URL}
    acceptingBookings: true
    bookingTimeAllowedInMinutes: 120
    recommendedCheckInTime: 5
    numberOfSeats: ${NUMBER_OF_SEATS:10}
    allowTimeExtension: true
    maximumTimeExtensionAllowedInMinutes: 30
    allowLateCheckIn: true
    allowedLateCheckInTimeInMinutes: 10
    allowEarlyCheckIn: true
    allowedEarlyCheckInMinutes: 5
    enablenotificationservice: ${ENABLE_NOTIFICATIONS_SERVICE:true}
    enableemailservice: ${ENABLE_EMAIL_SERVICE:true}
    sendStudentNotifications:
      viaWeb: ${library.properties.enablenotificationservice}
      viaMail: ${library.properties.enableemailservice}
      timeUpNotificationSubject: "Time's up!"
      timeUpNotificationBody: "Your booked time has ended."
      blackListNotificationSubject: "Account Suspended"
      blackListNotificationBody: "Your account has been suspended."
      timeAlmostUpNotificationSubject: "Time Almost Up"
      timeAlmostUpNotificationBody: "Your booking will end soon."
      studentKickedOutNotificationSubject: "Booking Terminated"
      studentKickedOutNotificationBody: "Your booking has been terminated."
    sendMessagesViaEmail: true
    managementservice:
      notifystudents: ${ENABLE_MANAGEMENT_NOTIFICATION_SERVICE:true}
      managementservicenotificationlist:
        - timeLeft: 15
          message: "15 minutes remaining"
        - timeLeft: 5
          message: "5 minutes remaining"
    readTimeoutInSeconds: 10
    connectTimeoutInSeconds: 10
    setOfAllowedFaculties:
      AllowedFaculties[0]:
        name: ENGINEERING
        departments:
          - ELE
          - MME
          - MME
      AllowedFaculties[1]:
        name: CIS
        departments:
          - CSC
          - MAC
          - LIS
      AllowedFaculties[2]:
        name: ARTS
        departments:
          - ENG
          - CIVIL
    enableSeatRandomization: true
    allowMultipleReservations: false
    allowAdvancedBookings: true
    maximumLimitPerDay: ${MAX_BOOKINGS_PER_DAY:2}
    enableLimitPerDay: true
    librarianSeatDto:
      reserveLibrarianSeat: true
      numberOfLibrarians: ${NUMBER_OF_LIBRARIANS:2}
      seatNumbers:
        - 2
        - 5
    allowMultipleTimeExtension: false