# the jwt key must be at least 256 bits
# the jwt key provided here is a dummy one, and should be replaced...
# the jwt key is to sign and also authenticate tokens....
# TODO Replace static Jwt
jwt:
  key: 3s4wk395383aka893948938zd8u0499a93jz9Anb949wi3ju982n387587za832bau384l384ha7293
  expirationTime: 120

server:
  port: 8080

Spring:
  application:
    name:
      LibReserve

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-gmail-username@gmail.com
    password: your-gmail-password
    properties:
      smtp:
      auth:
        true
      starttls:
        enable: true

  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    generate-unique-name: false
    name: LibReserve

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      springframework:
        security: DEBUG

library:
  properties:
    acceptingBookings: true
    bookingTimeAllowedInMinutes: 120
    numberOfSeats: 10
    allowTimeExtension: true
    maximumTimeExtensionAllowedInMinutes: 30
    recommended-check-in-time: 5
    allowLateCheckIn: true
    allowed-late-check-in-time-in-minutes: 10
    allowEarlyCheckIn: true
    allowedEarlyCheckInMinutes: 5
    sendNotifications: true
    sendEmails: true
    readTimeoutInSeconds: 10
    connectTimeoutInSeconds: 10
    reserveLibrarianSeat: true
    notificationTimeListInMinutes:
      - 30
      - 10
      - 5
    enableSeatRandomization: true
    universityUrl: "https://universitywebsite.com"